### ISSUE TITLE
reprise du modèle SQLite

### ISSUE THREAD

**Issue by architexte** [chartes/adele#1]
@MrGecko, commentaires pour la reprise de la base (forza !)
* chargement du XML : vérifier UTF-8 et résoudre les entités (attention au double quote)
* renommer table `author` en `editor` (Guyeotjeannin : auteur de la notice et non de l’acte)
* créér table `user` (atts: `firstname`, `lastname`, `passwd`, `mail`, `username` = jpilla)
* créer 3 users
* `document.copy_cent` : typer en integer pour les tris -> le romain est une vue
* rename `document.institution` en `document.institution-ref`
* rename `regeste`en `argument` : attention à l’import XML : ramasser les `div[@type="regeste"]`
* rename `date_cre` en `date_insert` (date de création en base du dossier)
* rename `date_maj` en `date_update` (date de maj en base du dossier)
* add `transcription.user-ref` pour lier une transcription à un utilisateur (contributeur)
* rename `traduction` en `translation` ; répercuter sur les `@`
* add `translation.user-ref` pour lier une transcription à un utilisateur (contributeur)
* renommer `traduction_ptr_table` en `alignment_translation` (renommer aussi les attributs -> `start`, `end`, etc.)
* `translation_alignment` : ajouter le premier segment (`ptr`) à la clé
* redéfinir clé `traduction_ptr_table`
* renommer `zone_facsimile` en `image_zone`
* redéfinir les attributs de `image_zone` pour autoriser les polygones et les cercles (`@coord`) ; `zone_url` devient `img_url` (une zone est une portion d’image ; une image est une image entière)
* créer une table `image` pour lier un document à son/ses images (url IIIF)
* renommer `facsimile_ptr_table` en `alignment_image`
* ajouter un `alignment_image.type` (`annotation`|`transcription`)
* parties du discours
  * créer une table nomenclature des parties : id, label, definition (anticiper i18n)
  * faire la liste des [parties](http://www.cei.lmu.de/VID/#VID_TOC_7) identifiées dans les dossiers theleme: adresse_universelle, suscription, salut, notification_universelle, corps, clause, clause_garantie, clause_renonciation, corroboration, date_temps
  * créer `alignment_discours` (attributs : `transcription_id`, `ptr_start`, `ptr_end`, `discours-type-id`, `note`)
* ajouter `type_acte.description`

* lier la transcription au document
* recenser les éléments contenus dans les transcriptions et proposer un formalisme simple pour éditeur en ligne (*mapping* HTML -> TEI)
  * `expan`
  * `note`
  * `term`
  * `hi`
  * `@` ?

# Documentation
* Produire adeel-schema.sql et le documenter
* Lier (autant que possible) le schéma SQL au TEI de sortie

#NB
* on ne peut pas aligner une traduction sans transcription

**Comment by MrGecko** [comment]
@architexte 
Pour info, voici les types de partie de discours recensés dans l'ensemble des dossiers : 
[https://github.com/chartes/adeel/blob/master/type_partie_discours.txt](url)
